platform :ios, '7.0'		#手机系统

target "WhereIs" do		#目标
pod 'AMap2DMap'			#2D地图
pod 'AMapSearch'		#地图搜索
pod 'Reachability', '3.2'	#网络监控
#pod 'AMap3DMap'		#3D地图，不能和2D一起用
#pod 'AMapNavi'			#导航
#pod 'CardboardSDK'		#GoogleVR


end